### ISSUE TITLE
OVIS Dataset Error

### ISSUE THREAD

**Issue by 1787594808** [sukjunhwang/VITA#11]
I successfully train and inference on youtubevis2019 and 2021, but it fails on OVIS. There is no error in the OVIS training process, but an error is reported when the last pth file is generated and reasoned, the following is my error:
```
-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/anaconda3/envs/vita/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/detectron2/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/VITA/train_net_vita.py", line 301, in main
    return trainer.train()
  File "/detectron2/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/detectron2/detectron2/engine/train_loop.py", line 165, in train
    self.after_train()
  File "/detectron2/detectron2/engine/train_loop.py", line 174, in after_train
    h.after_train()
  File "/detectron2/detectron2/engine/hooks.py", line 561, in after_train
    self._do_eval()
  File "/detectron2/detectron2/engine/hooks.py", line 529, in _do_eval
    results = self._func()
  File "/detectron2/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/VITA/train_net_vita.py", line 235, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/VITA/train_net_vita.py", line 119, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name, mapper=mapper)
  File "/detectron2/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/VITA/vita/data/build.py", line 199, in _test_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/VITA/vita/data/build.py", line 92, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/VITA/vita/data/build.py", line 92, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/VITA/vita/data/datasets/ytvis.py", line 294, in <lambda>
    DatasetCatalog.register(name, lambda: load_ytvis_json(json_file, image_root, name))
  File "/VITA/vita/data/datasets/ytvis.py", line 156, in load_ytvis_json
    ytvis_api = YTVOS(json_file)
  File "/VITA/vita/data/datasets/ytvis_api/ytvos.py", line 63, in __init__
    self.createIndex()
  File "/VITA/vita/data/datasets/ytvis_api/ytvos.py", line 71, in createIndex
    for ann in self.dataset['annotations']:
TypeError: 'NoneType' object is not iterable
```
Please author help me, thanks!

**Comment by sukjunhwang** [comment]
It seems like the code is wrongly accessing the YTVIS data loader instead of OVIS. Could you check if OVIS configurations are being used correctly?

**Comment by 1787594808** [comment]
Just now, I have re cloned the project , no files have been modified, and evaluated it using the model file provided by the author. The command is as follows:
`python train_net_vita.py --config-file configs/ovis/vita_R50_bs8.yaml --eval-only MODEL.WEIGHTS vita_r50_ovis.pth`
But still the above question. Is there a problem with the author's OVIS configuration file? Or is there a problem with my OVIS dataset? The following is my OVIS folder:
```
ovis
---train
     ---001ca3cb
          ................
---valid
     ---012b09a0
          ................
---annotation
     ---train.json
     ---valid.json
```
Because I can train normally, there seems to be no problem with file placement, but it just can't be evaluated.

**Comment by sukjunhwang** [comment]
https://github.com/sukjunhwang/VITA/blob/f274a4eef298660b034b8b2a39a05278ad85e62a/vita/data/datasets/builtin.py#L41-L42

Could you please check if valid.json is under the folder named ```annotations```, instead of ```annotation```?

**Comment by 1787594808** [comment]
Sorry, I missed an “s” in the folder description above. Because I can train and only reported this error during the evaluation, the folder should be fine.  Can the author re clone the project to evaluate ovis? My guess is that the author's code cannot correctly read the valid json file. If the author has not reported any errors, the author's code should have no problems, and I will find the problem myself. Thank you!

**Comment by 1787594808** [comment]
The code has two questions: Is reading the ovis dataset also using ytvis.py? The second is that valid.json is different from train.json, the "annotations" in valid.json is null. Why does it appear for `ann in self. dataset ['annotations']`?

**Comment by fbragman** [comment]
Hello - was a solution found to this? I'm trying to run the code from GenVis on `OVIS` and I'm also getting a `NoneType` error for annotations.

>   File "/home/felix/mlcore_pants/libs/genvis/vita/data/datasets/ytvis.py", line 337, in <lambda>
    DatasetCatalog.register(name, lambda: load_ytvis_json(json_file, image_root, name))
  File "/home/felix/mlcore_pants/libs/genvis/vita/data/datasets/ytvis.py", line 201, in load_ytvis_json
    ytvis_api = YTVOS(json_file)
  File "/home/felix/mlcore_pants/libs/genvis/vita/data/datasets/ytvis_api/ytvos.py", line 65, in __init__
    self.createIndex()
  File "/home/felix/mlcore_pants/libs/genvis/vita/data/datasets/ytvis_api/ytvos.py", line 73, in createIndex
    for ann in self.dataset["annotations"]:
TypeError: 'NoneType' object is not iterable

The model can train as `train.json` contains annotations.

Any ideas @sukjunhwang?

Many thanks!

**Comment by fbragman** [comment]
I see from the OVIS github page

> OVIS currently only allows evaluation on the codalab server. Please upload the generated result to [codalab server](https://competitions.codalab.org/competitions/32377) to see actual performances.

I guess that's why?
